#!/usr/bin/env node
import {readFileSync,writeFileSync,readdirSync,rmSync,mkdirSync,cpSync,existsSync} from 'node:fs';import {join,dirname} from 'node:path';import {fileURLToPath} from 'node:url';import {execFileSync} from 'node:child_process';import {createHash} from 'node:crypto';
const ROOT=join(dirname(fileURLToPath(import.meta.url)),'..'),SRC=join(ROOT,'src'),DIST=join(ROOT,'dist'),APP_ID='essay-evaluator',CORE_VERSION='1.0.0',CORE_DIR=join(ROOT,'vendor',`ghrab-ai-core-${CORE_VERSION}`),CORE_FILE=`ghrab-ai-core-${CORE_VERSION}.js`,CORE_MANIFEST=`ghrab-ai-core-manifest-${CORE_VERSION}.json`;
const fail=m=>{console.error('[build] CHYBA: '+m);process.exit(1)},log=m=>console.log('[build] '+m),sha=f=>createHash('sha256').update(readFileSync(f)).digest('hex');
for(const f of [CORE_FILE,CORE_MANIFEST])if(!existsSync(join(CORE_DIR,f)))fail('chybí Core artefakt '+f);const coreManifest=JSON.parse(readFileSync(join(CORE_DIR,CORE_MANIFEST),'utf8'));if(coreManifest.coreVersion!==CORE_VERSION||coreManifest.artifacts?.[CORE_FILE]?.sha256!==sha(join(CORE_DIR,CORE_FILE)))fail('GHRAB AI Core neprošel SHA-256 kontrolou');
const pkg=JSON.parse(readFileSync(join(ROOT,'package.json'),'utf8')),version=String(pkg.version||'').trim();if(!/^\d+\.\d+\.\d+$/.test(version))fail('neplatná verze');const inject=t=>String(t).replaceAll('__APP_VERSION__',version),readInjected=p=>inject(readFileSync(p,'utf8'));
rmSync(DIST,{recursive:true,force:true});mkdirSync(DIST,{recursive:true});const jsFiles=readdirSync(join(SRC,'js')).filter(f=>f.endsWith('.js')).sort((a,b)=>a.localeCompare(b,undefined,{numeric:true})),cssFiles=readdirSync(join(SRC,'styles')).filter(f=>f.endsWith('.css')).sort();
const template=readInjected(join(SRC,'index.template.html')),body=readInjected(join(SRC,'body.html')),styles=cssFiles.map(f=>`/* ${f} */\n${readInjected(join(SRC,'styles',f))}`).join('\n'),appModules=jsFiles.map(f=>`/* ${f} */\n${readInjected(join(SRC,'js',f))}`).join('\n');let app=readFileSync(join(CORE_DIR,CORE_FILE),'utf8')+'\n;\n'+appModules;
if(!appModules.includes(`version:'${version}'`))fail('RELEASE.version nebyla injektována');if((appModules.match(/\binit\(\);/g)||[]).length!==1)fail('aplikace musí mít jedno init()');let buildHash='';try{buildHash=execFileSync('git',['rev-parse','--short','HEAD'],{cwd:ROOT,stdio:['ignore','pipe','ignore']}).toString().trim()}catch{}if(buildHash)app=app.replace("build:'__BUILD__'",`build:'${buildHash}'`);
const html=template.replace('/*==HODNOTITEL_STYLES==*/',styles).replace('<!--==HODNOTITEL_BODY==-->',body);if(/HODNOTITEL_(STYLES|BODY)|__APP_VERSION__/.test(html+app))fail('zůstal build token');writeFileSync(join(DIST,'index.html'),html);writeFileSync(join(DIST,'app.js'),app);
for(const name of ['access-bootstrap.js','access-gate.css','manifest.webmanifest','sw.js'])writeFileSync(join(DIST,name),readInjected(join(SRC,name)));for(const name of ['assets','icons','vendor','rubric','manual','access','config','platform'])if(existsSync(join(SRC,name)))cpSync(join(SRC,name),join(DIST,name),{recursive:true});
cpSync(join(SRC,'ghrab-platform.consumer.json'),join(DIST,'ghrab-platform.consumer.json'));cpSync(join(SRC,'ai-operations.json'),join(DIST,'ai-operations.json'));const operations=JSON.parse(readFileSync(join(DIST,'ai-operations.json'),'utf8'));if(operations.appId!==APP_ID||operations.appVersion!==version||operations.coreVersion!==CORE_VERSION||operations.operations.length!==4)fail('neplatný ai-operations.json');for(const op of operations.operations)if(!appModules.includes(`'${op.operation}'`)&&!appModules.includes(`"${op.operation}"`))fail('integrace neobsahuje operaci '+op.operation);
const manifestText=readInjected(join(SRC,'studio-manifest.template.json')).replaceAll('__BUILD_TIME__',new Date().toISOString()),manifest=JSON.parse(manifestText);if(/produk|production/i.test(`${manifest.status?.cs||''} ${manifest.status?.en||''}`))fail('manifest nesmí deklarovat produkci');if(manifest.limits?.maxSeriesSize!==20)fail('manifest musí deklarovat limit 20');if(manifest.aiCore?.coreVersion!==CORE_VERSION||manifest.aiCore?.serverReady!==true||manifest.aiCore?.conformancePassed!==true)fail('studio-manifest nemá P1 AI Core metadata');writeFileSync(join(DIST,'studio-manifest.json'),manifestText);writeFileSync(join(DIST,'.nojekyll'),'');
const pwa=JSON.parse(readFileSync(join(DIST,'manifest.webmanifest'),'utf8'));if(pwa.id!=='/Hodnotitel-maturitnich-slohu/'||pwa.start_url!=='./')fail('PWA identita musí zůstat stabilní');try{execFileSync(process.execPath,['--check',join(DIST,'app.js')],{stdio:'pipe'});execFileSync(process.execPath,['--check',join(DIST,'access-bootstrap.js')],{stdio:'pipe'})}catch(error){fail('výsledný JavaScript je neplatný: '+String(error.stderr||error.message))}
const rubric=JSON.parse(readFileSync(join(DIST,'rubric','rubric-v2026.04.27-r1.json'),'utf8'));if(rubric.version!=='2026.04.27-r1')fail('nesouhlasí rubrika');log(`HOTOVO · ${version} · Core ${CORE_VERSION} SHA-256 OK · ${operations.operations.length} operace · ${jsFiles.length} JS modulů`);

// P2: canonical cross-application platform post-processing.
await import("./apply-ghrab-platform.mjs");
